module(load="imudp")
input(type="imudp" port="514")
module(load="imtcp")
input(type="imtcp" port="514")
if $fromhost-ip == '10.0.0.241' then {
    action(type="omfile" file="/var/log/fortianalyzer/forti.log")
    stop
}
